services:
  - type: web
    name: project-2
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install firefox
    startCommand: gunicorn app:app --timeout 120 --workers 1
