services:
  - type: web
    name: quiz-solver-project
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      pip install -r requirements.txt
      playwright install firefox --with-deps
    startCommand: gunicorn app:app --timeout 300 --workers 1 --bind 0.0.0.0:$PORT
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/.cache/ms-playwright
